<?php

namespace Afpa\PokerGameBundle\Repository;

/**
 * TablePokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablePokerRepository extends \Doctrine\ORM\EntityRepository
{
}
